<?xml version="1.0" ?>
<robot name="box_bot_rgbd" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find box_bot_description)/robot/materials.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/properties.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/macros.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/wheels.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/caster_wheels.xacro" />  
  <xacro:include filename="$(find box_bot_description)/robot/box_bot_body.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/box_bot.gazebo" />

  <!-- Depth camera macro -->
  <xacro:macro name="depth_camera" params="name parent *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${name}_link" />
    </joint>
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 0.1" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 0.1" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.1" />
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>
    </link>
    <gazebo reference="${name}_link">
      <sensor type="depth" name="${name}_sensor">
        <camera>
          <horizontal_fov>1.047</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
          </image>
          <clip>
            <near>0.01</near>
            <far>10</far>
          </clip>
        </camera>
        <plugin name="${name}_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>30.0</updateRate>
          <cameraName>${name}</cameraName>
          <imageTopicName>/${name}/depth/image_raw</imageTopicName>
          <cameraInfoTopicName>/${name}/depth/camera_info</cameraInfoTopicName>
          <frameName>${name}_link</frameName>
          <pointCloudTopicName>/${name}/depth/points</pointCloudTopicName>
          <pointCloudCutoff>0.01</pointCloudCutoff>
          <distortionK1>0</distortionK1>
          <distortionK2>0</distortionK2>
          <distortionK3>0</distortionK3>
          <distortionT1>0</distortionT1>
          <distortionT2>0</distortionT2>
          <hackBaseline>0</hackBaseline>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
          
  
  <xacro:box_bot_body parent_name="${base_name}"/>

  
  <xacro:link_wheel name="right_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_right_wheel" parent="${base_name}" child="right_wheel" origin_xyz="0 ${base_box_x / 2.0} ${-1.0 * wheel_radius}" />

  <xacro:link_wheel name="left_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_left_wheel" parent="${base_name}" child="left_wheel" origin_xyz="0 ${-1.0 * base_box_x / 2.0} ${-1.0 * wheel_radius}" />


  <xacro:caster_wheel parent="chassis" caster_wheel_name="front" origin_xyz="${(base_box_x / 2.0) - wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
  <xacro:caster_wheel parent="chassis" caster_wheel_name="back" origin_xyz="${(-1.0 *base_box_x / 2.0) + wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
  
        <!-- Add depth camera to the robot -->
  <xacro:depth_camera name="depth_camera" parent="${base_name}">
  <origin xyz="0 0 ${base_box_x / 2.0}" rpy="0 0 0" />
  </xacro:depth_camera>
          
</robot>
